server:
  port: 8090

spring:
  application:
    name: notification-ms
  datasource:
    username: "admin"
    password: "admin_password"
    url: jdbc:postgresql://localhost:5432/notification
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: "true"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}