server:
  port: 8080

spring:
  application:
    name: customer-ms
  datasource:
    username: "admin"
    password: "admin_password"
    url: jdbc:postgresql://localhost:5432/customer
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: "true"

client:
  url:
    fraudURL: http://fraud-ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}


# We're overriding instance Id since my ${spring.cloud.client.hostname} contains ê
# See https://cloud.spring.io/spring-cloud-static/Edgware.SR6/multi/multi__service_discovery_eureka_clients.html#_changing_the_eureka_instance_id