server:
  port: 8080

spring:
  application:
    name: customer-ms
  datasource:
    username: "admin"
    password: "admin_password"
    url: jdbc:postgresql://localhost:5432/customer
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: "true"

client:
  url:
    fraudURL: http://localhost:8081